Add two new small sbin utils. gdmopen is like open (based on it) but
Wed Aug 22 23:01:59 2001  George Lebl <jirka@5z.com>

	* configure.in, Makefile.am, utils/gdmopen.c, utils/gdmaskpass.c:
	  Add two new small sbin utils.  gdmopen is like open (based on it)
	  but better suited for gdm.  Exitcode is returned so no temp files
	  are needed.  Process is cleaned up on a signal, the new vt is
	  deallocated after use.  And unlike openvt this thing actually waits
	  for the child.  Gdmaskpass just asks for the root password, for
	  use in the XKeepsCrashing script.  Both of these things will only
	  run as root as I'm too paranoid and it doesn't make sense for
	  them to run otherwise for gdm anyway.

	* configure.in: Fix sbin expansion.

	* daemon/gdm.c, daemon/misc.[ch], daemon/slave.c, daemon/server.c:
	  Use gdmopen to run dialog and add helper functions for doing this.

	* daemon/gdm.h, daemon/slave.c, daemon/server.[ch]:  When a server is
	  busy, ask the user if we want to run it on a new display number
	  or retry.

	* daemon/gdm.c, daemon/misc.c, daemon/slave.c: Make sure to whack
	  any extra helper processes we launch when we are killed so that
	  we don't leave things like 'dialog' processes around

	* daemon/gdm.c, config/XKeepsCrashing:  Use gdmaskpass, ask if
	  the user wants to view X logs if X is crashing.  And use gdmopen
	  in the script and correctly abort with exit 32.  Also make it
	  not use the ugly tempfile stuff (Though a tempfile is still given
	  to the script for now)

	* gdm.spec.in: raise epoch to 1, people abuse this field, and if they
	  do abuse it again and raise it beyond 1, I'll just max it out since
	  it makes package upgrading not work.

	* daemon/slave.c, daemon/verify-(pam|crypt|shadow).c: add
	  /sbin/nologin as a thing to test for for disabled logins in
	  addition to /bin/false and /bin/true (it worked, but this adds a
	  nicer message)

	* daemon/xdmcp.c: fix a warning.

	* gui/gdmflexiserver.desktop.in: kill TryExec here

diff --git a/config/XKeepsCrashing b/config/XKeepsCrashing
--- a/config/XKeepsCrashing
+++ b/config/XKeepsCrashing
@@ -12,68 +12,89 @@
 # The second argument is a temporary file we can use
 #
 # $3 = 'Your X server is b0rk I will disable this server'
-# $4 = 'Your X server is b0rk would you like to try to reconfigure it?"
+# $4 = 'Would you like to try to reconfigure your server?"
 # $5 = 'Please type in the root password'
 # $6 = 'I will now restart the X server again'
 # $7 = 'I will disable this X server'
+# $8 = 'Your X server is b0rk, do ya wanna view X logs?'
+
+# there are some env vars defined:
+# XLOG = the log file for the X server
+# BINDIR = location of gdm binaries
+# SBINDIR = location of gdm system binaries
+
+# return values are
+# 0 = try again, runs this server again
+# 1 = abort this display, removes this server from the list
+# 32 = something went very wrong, things will just get logged.
+#      this means this script didn't work so do alternative things
+#      to tell the user if possible
+
+# we require "gdmopen", to open a console, because we really don't
+# have one.  Perhaps someone should try to figure out some shell
+# black magic to get this to work on other then linux systems
+if test ! -x $SBINDIR/gdmopen ; then
+  exit 32
+fi
 
 # when we run ourselves from the open we will pass a -noopen argument
 if test x$1 = x-noopen ; then
-	shift
+  shift
 else
-	TEMPFILE="$2"
-	# we require "open", to open a console, because we really don't
-	# have one.  Perhaps someone should try to figure out some shell
-	# black magic to get this to work on other then linux systems
-	if test -x /usr/bin/open ; then
-		/usr/bin/open -s -w -- $0 -noopen "$@"
-		if grep TRYAGAIN "$TEMPFILE" >/dev/null ; then
-			exit 0
-		else
-			exit 1
-		fi
-	else
-		exit 1
-	fi
+  $SBINDIR/gdmopen $0 -noopen "$@"
+  exit $?
 fi
 
 SETUP=`which $1`
-TEMPFILE="$2"
 DIALOG=`which dialog`
 if test x$DIALOG = x ; then
-	DIALOG=`which gdialog`
+  DIALOG=`which gdialog`
+fi
+if test -x $SBINDIR/gdmaskpass ; then
+  ASKPASS=$SBINDIR/gdmaskpass
+else
+  ASKPASS=
 fi
 
 clear
 
 # Note, dialog required, though this script could be fixed to not require it
 # I suppose
-if test x = x$SETUP -o x = x$DIALOG -o x = x$TEMPFILE ; then
+if test x = x$SETUP -o x = x$DIALOG ; then
+  echo =======================================================================
+  echo 
+  cat $XLOG
+  echo 
   echo =======================================================================
   echo
   echo  "$3"
   echo
   echo =======================================================================
   read
-  if test x != x$TEMPFILE ; then
-  	echo ABORT > $TEMPFILE
-  fi
   exit 1
+fi
+
+if $DIALOG --yesno "$8" 10 50 ; then 
+  $DIALOG --textbox $XLOG 22 76
 fi
 
 if $DIALOG --yesno "$4" 10 50 ; then 
   clear
   echo
   echo "$5"
-  # dirty trick to fool su into asking the root password even if we're
-  # root
-  su nobody -c "su -c $SETUP"
+  if test x$ASKPASS = x ; then
+    # dirty trick to fool su into asking the root password even if we're
+    # root
+    su nobody -c "su -c $SETUP"
+  else
+    if $ASKPASS ; then
+      $SETUP
+    fi
+  fi
   clear
   $DIALOG --msgbox "$6" 8 50
-  echo TRYAGAIN > $TEMPFILE
   exit 0
 else
   $DIALOG --msgbox "$7" 8 50
-  echo ABORT > $TEMPFILE
   exit 1
 fi
